// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCO4KHsRebwO_716ljuiPEGWd3pPqRCFZA',
    appId: '1:749115404987:web:b410e19efd5a3e3d23ef9e',
    messagingSenderId: '749115404987',
    projectId: 'chat-c0d8a',
    authDomain: 'chat-c0d8a.firebaseapp.com',
    storageBucket: 'chat-c0d8a.appspot.com',
    measurementId: 'G-L1J7JJBB0F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBpbUrcy4hvqN-MWqPCufZolz95MIs7g9k',
    appId: '1:749115404987:android:94b8cefd3d34caf423ef9e',
    messagingSenderId: '749115404987',
    projectId: 'chat-c0d8a',
    storageBucket: 'chat-c0d8a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCPoBX6vfc8zWGxYZHNfspDG3LyATbr3bU',
    appId: '1:749115404987:ios:12447e3b8f2345f223ef9e',
    messagingSenderId: '749115404987',
    projectId: 'chat-c0d8a',
    storageBucket: 'chat-c0d8a.appspot.com',
    iosBundleId: 'com.example.chat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCPoBX6vfc8zWGxYZHNfspDG3LyATbr3bU',
    appId: '1:749115404987:ios:a401a624d715ca6323ef9e',
    messagingSenderId: '749115404987',
    projectId: 'chat-c0d8a',
    storageBucket: 'chat-c0d8a.appspot.com',
    iosBundleId: 'com.example.chat.RunnerTests',
  );
}
